### ISSUE TITLE
New release - iptv manager

### ISSUE THREAD

**Issue by piejanssens** [add-ons/plugin.video.yelo#26]
Could there be a new release submitted to the Kodi repo now that IPTV Manager is released on the repo?

@dagwieers @michaelarnauts @shycoderX

**Comment by dagwieers** [comment]
Yes, that was always the intention.
Let me check this weekend if there's anything we still need to do.

Thanks for reminding me.

**Comment by vossim** [comment]
Any update on this?

**Comment by dagwieers** [comment]
@vossim I proposed a release workflow now to @shycoderX, after this if there are no outstanding issues, I think we can release.

**Comment by emversch** [comment]
Any updates? Latest version on Kodi is still 0.0.9. Devs of IPTV said 1.0.0 is supported but not 0.0.9

**Comment by dagwieers** [comment]
Only @shycoderX can release to the Kodi repository.

**Comment by michaelarnauts** [comment]
@shycoderX would you mind looking at #30 and #31 so a new release with these fixes can be pushed to the repository?

**Comment by dagwieers** [comment]
Now that Kodi v19 Beta has been released this is indeed impacting users that (automatically) were updated to Kodi v19. (e.g. if you are a Kodi Android beta user like me and @Forceflow).

**Comment by shycoderX** [comment]
> @shycoderX would you mind looking at #30 and #31 so a new release with these fixes can be pushed to the repository?

Both are now approved!
