### ISSUE TITLE
Login failed error since a week

### ISSUE THREAD

**Issue by maanwater** [add-ons/plugin.video.yelo#28]
Hello

I've been using this addon for several months now, but since somewhere last week I can no longer open the addon. Instead I am welcomed with a Login failed error message - while my logon details are still the same (loggin onto yeloplay.be still works).

[edit: I am using Kodi on Libreelec 9.2.4]

Any idea what could be causing this sudden behaviour?

I checked the logs and found this error:
/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
InsecureRequestWarning

Thanks in advance
maanwater

**Comment by dagwieers** [comment]
That error you are seeing is not related to your problem. It is something we ought to fix, but harmless in itself.

**Comment by dagwieers** [comment]
We would need a Kodi debug log in order to understand what is going on.

**Comment by maanwater** [comment]
I hope this is what you need: http://paste.kodi.tv/ariturahav

**Comment by dagwieers** [comment]
I just wanted to add that the issue was indeed related to data.json not being available. (Which in itself is an issue, why would it have gone missing?)

But the second log does not show a real error I can relate to. Maybe restarting Kodi has an effect?

**Comment by maanwater** [comment]
Restarting: favourite solution :) Unfortunately no luck. Could it be related to a change in my Telenet account?

**Comment by shycoderX** [comment]
@maanwater can you please enable debug logging? https://kodi.wiki/view/Log_file/Easy#:~:text=Enable%20the%20setting%20Enable%20debug,Shift%20%2B%20d%20on%20a%20keyboard

**Comment by maanwater** [comment]
The latest update resolves this issue for me. So thank you very much for the continuous development.
