### ISSUE TITLE
TV-gids refresht niet automatisch

### ISSUE THREAD

**Issue by Rphil29** [add-ons/plugin.video.yelo#36]
Ik gebruik Yelo in combinatie met IPTV manager. Ik heb Kodi zo ingesteld dat ik bij het opstarten onmiddellijk naar de tv gids ga, maar de tv gids van Yelo refresht niet automatisch. Andere addons zoals Vrt Nu of Vier-Vijf-Zes doen dat wel. De tv gids van Yelo blijft altijd hangen op 4u 's morgens. Ik kan dan niet vooruit of achteruit gaan in de tv gids. Als ik naar de groep van bijvoorbeeld Vrt Nu ga, gaat dat wel. 

Doe ik iets fout met mijn instellingen? Of laadt de tv gids van Yelo gewoon niet automatisch?

**Comment by michaelarnauts** [comment]
@Rphil29 klopt. als ik juist ben is dit wel ondertussen gefixt in de laatste master branch. Het probleem was dat er maar een EPG werd opgehaald voor de huidige dag, en als IPTV Manager maar om de 24u refresht, ga je altijd een window hebben zonder gids-data.

Via deze zip zou het wel moeten werken: https://github.com/add-ons/plugin.video.yelo/archive/master.zip

**Comment by Duriauke** [comment]
Ik heb sinds kort de yelo app , en iptvmanager gedownload via kodi. Nu had ik na 1 dag het probleem dat ik mijn tvgids niet meer verder als 5 u'smorgens kon raadplegen. Heb in een onderstaand bericht op deze pagina gezien dat er een zipfile was die dit probleem zou oplossen. Helaas constateer ik na het downloaden hiervan nog steeds hetzelfde probleem. Kunnen jullie me verder opweg helpen om dit probleem op te lossen. Ook het herbekijken van uitgestelde programma's lukt me niet. Moet ik nog iets anders in de settings veranderen. Alvast bedankt voor de hulp en natuurlijk ook bedankt voor het maken van zulke leuke addons in tijden waar je nog steeds geen native app van yelo play voor android tv hebt. Ik weet dat je nu telenet tv hebt voor android tv maar na een gesprek met een medewerker van telenet blijkt dat er momenteel niet geswitched kan worden wegens het ontbreken sinds maart al van hun nieuwe digicorder.

**Comment by peno64** [comment]
@Duriauke Zie het bericht van @michaelarnauts van hierboven. Het is niet voldoende om de yelo app via kodi te downloaden om dit te fixen. Je moet  de ontwikkelversie van de yelo addon downloaden (https://github.com/add-ons/plugin.video.yelo/archive/master.zip) en installeren zodat de tv gids over een langere periode van 24 uur wordt opgehaald.

**Comment by dagwieers** [comment]
Tijd om een nieuwe release te doen als meer gebruikers er last van hebben?

**Comment by peno64** [comment]
Ik zou zeggen ja. De laatste week heb ik niet meer gehad dat de gids leeg is.

**Comment by base08** [comment]
De laatste commit van 1.0.1 heeft de probleem van de lege gids opgelost! 👍🏻

**Comment by dagwieers** [comment]
Ik denk dat we dit issue kunnen afsluiten. Bedankt allemaal!
