### ISSUE TITLE
Not an issue but a request/challenge regarding the possibility of zapping

### ISSUE THREAD

**Issue by base08** [add-ons/plugin.video.yelo#6]
As the title suggests this is a request for an implementation of a zapping system with the use of previous or next buttons (like you would change a video on a playlist). Is this possible?

**Comment by shycoderX** [comment]
> As the title suggests this is a request for an implementation of a zapping system with the use of previous or next buttons (like you would change a video on a playlist). Is this possible?

I'll look into it when I have some time. In the meantime feel free to do a PR if you come up with a solution yourself :)

**Comment by base08** [comment]
This seems to be shaping up as an amazing way to solve it...

**Comment by shycoderX** [comment]
> This seems to be shaping up as an amazing way to solve it...
> https://github.com/add-ons/service.iptv.manager

Version 1.0.0 does now support iptv manager. Remember to login first as you used to before using iptvmanager.
