### ISSUE TITLE
Have a proper repository for Yelo add-on

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.yelo#8]
It would be nice if the Yelo add-on had a separate repository that only hosted the add-on (and not everything from repo-plugins and those branches).

It would help for others to contribute, and it helps to get e.g. unit testing integrated as well. Things that are not allowed in repo-plugins.

It would also be useful for people to test out the latest changes by simply downloading the ZIP from GitHub.

**Comment by michaelarnauts** [comment]
This is done now!

-> https://github.com/add-ons/plugin.video.yelo

**Comment by dagwieers** [comment]
Fantastic! I would like to add the sanity and integration tests we use for other add-ons.
